import React from 'react'
import './Coreteam.css'
import { Container,Row,Col} from 'react-bootstrap';
import MemberCard from './MemberCard';
function Coreteam() {
    return (
        <Container fluid className="coreteam">
            <Row className="ourMentorsHeading justify-content-center">
                <h1 >Our Mentors</h1>
            </Row>
            <Row className="justify-content-center" sm={1} md={2} lg={3}>
                <Col md={3} className="mentorcards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Mentor" designation="HOD, CSE Department" name="Ajay Sharma" instagram="https://www.instagram.com/" facebook="https://www.facebook.com/" linkedin="https://www.linkedin.com/in/dr-ajay-sharma-3619021b/" gmail="mailto:hod.cse@srmuniversity.ac.in"/></Col>
                <Col md={5} className="mentorcards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Mentor" designation="Director of International Affairs" name="Manoj Kutty" instagram="https://www.instagram.com/srmuniversitydelhincr/" facebook="https://www.facebook.com/" linkedin="https://www.linkedin.com/in/manojl/" gmail="mailto:mailto:admissions.ir@srmuniversity.ac.in"/></Col>
                <Col md={3} className="mentorcards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Mentor" designation="Professor, CSE Department" name="Dr. M. Mohan" instagram="https://www.instagram.com/" facebook="https://www.facebook.com/" linkedin="https://www.linkedin.com/feed/" gmail="mailto:m.mohan@srmuniversity.ac.in"/></Col>
            </Row>
            <Row className="ourCoreHeading justify-content-center">
                <h1 >Our Core Members</h1>
            </Row>
            <Row sm={1} md={2} lg={3} className="justify-content-center">
                <Col className="corecards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Founder & President" designation="Student, III Year" name="Jai Sanghi" instagram="https://www.instagram.com/jaysh_sanghi/" facebook="https://www.facebook.com/profile.php?id=100008203244175" linkedin="https://www.linkedin.com/in/jai-sanghi/" gmail="mailto:jaykumar9246@gmail.com"/></Col>
                <Col className="corecards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Vice President" designation="Student, III Year" name="Vansh Agarwal" instagram="https://instagram.com/vansh_aga?igshid=52o3calgq2jy" facebook="https://www.facebook.com/vansh.agrawal.942" linkedin="https://www.linkedin.com/in/vansh-agrawal-779818194/" gmail="mailto:vanshagrawal876@gmail.com"/></Col>
                <Col className="corecards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Outreach and community manager" designation="Student, III Year" name="Dev Garg" instagram="https://www.instagram.com/dev.garg.5220/" facebook="https://www.facebook.com/dev.garg.5220" linkedin="http://linkedin.com/in/dev-garg-0195581a2" gmail="mailto:devgarg9966@gmail.com"/></Col>
                <Col className="corecards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Manager" designation="Student, III Year" name="Shivjyoti Dalai" instagram="https://www.instagram.com/_.taken_by_whisky._/" facebook="https://www.facebook.com/" linkedin="https://www.linkedin.com/in/shivjyoti-dalai/" gmail="mailto:shivjyotidalai@gmail.com"/></Col>
                <Col className="corecards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="General Secretory" designation="Student, IV Year" name="Archit Raj" instagram="https://instagram.com/i_am_archit_raj?igshid=eics9cpt1a00" facebook="https://www.facebook.com/archit.raj.5" linkedin="https://www.linkedin.com/in/archit-raj-b07249175" gmail="mailto:archit.raj23@gmail.com"/></Col>
                <Col className="corecards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Serjeant at arms" designation="Student, III Year" name="Jatin Rajput" instagram="https://instagram.com/__jatin__rajput?igshid=uhj6qdoylq4u" facebook="https://www.facebook.com/jatinkurajput" linkedin="https://www.linkedin.com/in/jatin-kumar-8252921b7" gmail="mailto:jk32600ku@gmail.com"/></Col>
            </Row>
            <Row className="ourTrainersHeading justify-content-center">
                <h1 >Our Trainers</h1>
            </Row>
            <Row sm={1} md={2} lg={3} className="justify-content-center">
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Competitive Trainer" designation="Student, III Year" name="Vedansh Kumar" instagram="https://www.instagram.com/vedanshh_/" facebook="https://www.facebook.com/" linkedin="https://www.linkedin.com/in/vedansh-kumar-27822410b/" gmail="mailto:vedansh21.2000@gmail.com"/></Col>
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Competitive Trainer" designation="Student, IV Year" name="Namrata Sharma" instagram="https://instagram.com/namrata.ss07?igshid=gi7ncfaavx1y" facebook="https://www.facebook.com/namrata.ss07" linkedin="https://www.linkedin.com/in/namratasharma28" gmail="mailto:namrata.ss07@gmail.com"/></Col>
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Competitive Trainer" designation="Student, IV Year" name="Dipanshu Jain" instagram="https://instagram.com/dipanshu.jain88?igshid=1p7nslhs6wkzb" facebook="https://www.facebook.com/dipanshu.jain.12" linkedin="https://www.linkedin.com/in/dipanshu-jain-backend-developer/" gmail="mailto:dipanshujain895@gmail.com"/></Col>
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="C Trainer" designation="Student, III Year" name="Dev Thakkar" instagram="https://www.instagram.com/dev2326/" facebook="https://www.facebook.com/dev.thakkar.2326" linkedin="https://www.linkedin.com/in/dev-thakkar-a14581189/" gmail="mailto:devparasthakkar@gmail.com"/></Col>
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="JavaScript Trainer" designation="Student, IV Year" name="Prateek Madan" instagram="https://instagram.com/prateekmadan14?igshid=13hb2oxo5trc4" facebook="https://www.facebook.com/prateek.madan.5" linkedin="https://www.linkedin.com/in/prateekmadan" gmail="mailto:prateekmadan14@gmail.com"/></Col>
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="JavaScript Trainer" designation="Student, IV Year" name="Aditya Bhardwaaj" instagram="https://instagram.com/mr_writer_1999?igshid=1w5c29j42v0ex" facebook="https://www.facebook.com/aditya.bhardwaj.507464" linkedin="https://www.linkedin.com/in/aditya-bhardwaj-831b02135" gmail="mailto:bhardwaj.aditya99@gmail.com"/></Col>
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Python Trainer" designation="Student, III Year" name="Jai Sanghi" instagram="https://www.instagram.com/jaysh_sanghi/" facebook="https://www.facebook.com/profile.php?id=100008203244175" linkedin="https://www.linkedin.com/in/jai-sanghi/" gmail="mailto:jaykumar9246@gmail.com"/></Col>
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Python Trainer" designation="Student, III Year" name="Dev Garg" instagram="https://www.instagram.com/dev.garg.5220/" facebook="https://www.facebook.com/dev.garg.5220" linkedin="http://linkedin.com/in/dev-garg-0195581a2" gmail="mailto:devgarg9966@gmail.com"/></Col>
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Java Trainer" designation="Student, III Year" name="Vansh Agarwal" instagram="https://instagram.com/vansh_aga?igshid=52o3calgq2jy" facebook="https://www.facebook.com/vansh.agrawal.942" linkedin="https://www.linkedin.com/in/vansh-agrawal-779818194/" gmail="mailto:vanshagrawal876@gmail.com"/></Col>
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Java Trainer" designation="Student, III Year" name="Krapa Kartik" instagram="https://www.instagram.com/karthik.krapa_0618/" facebook="https://www.facebook.com/karthik.krapa.1/" linkedin="https://www.linkedin.com/in/karthik-krapa-213bb11a0/" gmail="mailto:karthik.krapa18@gmail.com"/></Col>
                <Col className="trainercards"><MemberCard image="https://www.pngitem.com/pimgs/m/402-4023350_transparent-member-icon-png-member-logo-png-download.png" position="Java Trainer" designation="Student, II Year" name="Aditya Thakur" instagram="https://www.instagram.com/adityathakurxd/" facebook="https://www.facebook.com/" linkedin="https://www.linkedin.com/in/adityathakurxd" gmail="mailto:aditya.thakur19@stu.srmuniversity.ac.in"/></Col>
            </Row>
        </Container>
    )
}

export default Coreteam
